/**
 * OpenTelemetry SDK initialisation.
 *
 * Must be imported FIRST in src/index.js (before any other module) so that
 * the SDK is registered before tracers and meters are acquired.
 *
 * Exports:
 *   counters   — Prometheus counters keyed by metric name
 *   histograms — Prometheus histograms
 *   gauges     — Observable gauges (registered via callbacks)
 *
 * Backends (all optional, controlled by env vars):
 *   Traces  → OTLP HTTP → Jaeger (OTEL_EXPORTER_OTLP_ENDPOINT)
 *   Metrics → PrometheusExporter on :9464 (scraped by Prometheus sidecar)
 */

import { NodeSDK } from '@opentelemetry/sdk-node';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { PrometheusExporter } from '@opentelemetry/exporter-prometheus';
import { Resource } from '@opentelemetry/resources';
import { SEMRESATTRS_SERVICE_NAME } from '@opentelemetry/semantic-conventions';
import { metrics } from '@opentelemetry/api';

const OTLP_ENDPOINT = process.env.OTEL_EXPORTER_OTLP_ENDPOINT ?? 'http://localhost:4318/v1/traces';
const PROMETHEUS_PORT = parseInt(process.env.PROMETHEUS_PORT ?? '9464', 10);

const prometheusExporter = new PrometheusExporter({ port: PROMETHEUS_PORT });

const sdk = new NodeSDK({
  resource: new Resource({ [SEMRESATTRS_SERVICE_NAME]: 'claudebot' }),
  traceExporter: new OTLPTraceExporter({ url: OTLP_ENDPOINT }),
  metricReader: prometheusExporter,
});

sdk.start();
console.log(`[telemetry] OTel SDK started — metrics on :${PROMETHEUS_PORT}, traces → ${OTLP_ENDPOINT}`);

// Flush on graceful shutdown
process.on('SIGTERM', () => sdk.shutdown().catch(() => {}));
process.on('SIGINT', () => sdk.shutdown().catch(() => {}));

// ─── Meter + instruments ──────────────────────────────────────────────────────

const meter = metrics.getMeter('claudebot', '2.0.0');

export const counters = {
  messages:        meter.createCounter('bot_messages_total',          { description: 'Total messages received' }),
  toolUse:         meter.createCounter('bot_tool_use_total',          { description: 'Tool use blocks counted across all sessions' }),
  skillsGenerated: meter.createCounter('bot_skills_generated_total',  { description: 'Skills generated by dreaming loop' }),
  dreamingReviews: meter.createCounter('bot_dreaming_reviews_total',  { description: 'Thread reviews run by dreaming curator' }),
  remindersFired:  meter.createCounter('bot_reminders_fired_total',   { description: 'Reminders delivered' }),
  gatewayFailures: meter.createCounter('bot_gateway_health_failures', { description: 'Gateway health check failures' }),
};

export const histograms = {
  gatewayDuration: meter.createHistogram('bot_gateway_request_duration', {
    description: 'AI gateway request duration in ms',
    unit: 'ms',
  }),
};

// bot_active_threads — observable gauge backed by a DB query registered by scheduler
export const gauges = {
  activeThreads: meter.createObservableGauge('bot_active_threads', {
    description: 'Threads with activity in last 24h',
  }),
};
